In [25]:
# prevent GPU allocation problems
import os
os.environ["CUDA_VISIBLE_DEVICES"]="-1"
import sys
sys.path.append('..')

from keras.models import load_model
import numpy as np

from load_data import get_train_data, gen_test_data

In [27]:
!pwd

/d/sagniD/sp19/mldecal/mld-hackathon/notebooks


In [50]:
final_model = load_model('../models/ckpt_model_2_19.h5', compile=False)
final_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_20 (InputLayer)        (None, 784)               0         
_________________________________________________________________
dense_39 (Dense)             (None, 40)                31360     
_________________________________________________________________
dense_40 (Dense)             (None, 1)                 40        
Total params: 31,400
Trainable params: 31,400
Non-trainable params: 0
_________________________________________________________________


In [68]:
r = -2.057989149761852e-05
decision_score = lambda img: final_model.predict(img) - r
decision = lambda d_score: 1 - (d_score >= 0).astype(np.int)  # d_score >= 0 => in-distribution -> 0

In [77]:
NUM_TEST = 1024
test_x, _ = gen_test_data(NUM_TEST)

# for i in range(len(test_x)):
decision_scores = decision_score(test_x.reshape(NUM_TEST, -1))
decisions = decision(decision_score(test_x.reshape(NUM_TEST, -1)))

In [54]:
final_model.predict(test_x[0].reshape(1, -1))

array([[4.117793e-05]], dtype=float32)

In [74]:
np.count_nonzero(decisions == 0)

1024

In [81]:
decision_score(np.random.uniform(-1., 1., (10, 784)).astype(np.float32)) + r

array([[4.1177365e-05],
       [4.1177758e-05],
       [4.1177656e-05],
       [4.1177860e-05],
       [4.1177991e-05],
       [4.1177984e-05],
       [4.1177729e-05],
       [4.1177984e-05],
       [4.1177926e-05],
       [4.1177795e-05]], dtype=float32)

In [75]:
decisions

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [82]:
decision_scores + r

array([[4.1177278e-05],
       [4.1177336e-05],
       [4.1177285e-05],
       ...,
       [4.1177358e-05],
       [4.1177358e-05],
       [4.1177358e-05]], dtype=float32)